import type { JavaCategory } from "./types"

export const JAVA_CATEGORIES: JavaCategory[] = [
  {
    slug: "dates",
    name: "日付・時刻",
    articleCount: 11,
    summary: "営業日、祝日、和暦、タイムゾーンなど、日本語圏の実務処理を優先する。",
    priority: "high",
    purpose: "締日、帳票、海外時差のように実務で詰まりやすい日付処理を、標準 API で迷わず扱えるようにする。",
    audience: "業務システム、バッチ、帳票、外部連携の日付処理を担当する開発者。",
    featuredTopics: ["営業日計算", "日本の祝日判定", "和暦変換", "タイムゾーン差分"],
  },
  {
    slug: "validation",
    name: "入力値バリデーション",
    articleCount: 5,
    summary: "数値、文字列、日付、業務ルールの検証を扱う。",
    priority: "high",
    purpose: "金額、割合、単位のように業務ロジックへ直結する入力値を、破綻しにくい設計で扱えるようにする。",
    audience: "画面入力、CSV 取込、帳票計算、請求ロジックを扱う開発者。",
    featuredTopics: ["消費税計算", "割合・増減率", "単位変換"],
  },
  {
    slug: "db",
    name: "データベース",
    articleCount: 3,
    summary: "JDBC、プリペアドステートメント、トランザクションの基礎を押さえる。",
    priority: "high",
    purpose: "JDBC の基本操作を業務コードの前提に合わせて整理する。",
    audience: "保守案件や社内システムで JDBC を扱う開発者。",
    featuredTopics: ["JDBC 接続", "PreparedStatement", "トランザクション"],
  },
  {
    slug: "fileio",
    name: "ファイルI/O",
    articleCount: 11,
    summary: "CSV、properties、NIO、JSON、XML、全銀フォーマットなど業務で触れる入出力をまとめる。",
    priority: "high",
    purpose: "ファイル読込や出力を例外処理込みで安全に扱えるようにする。",
    audience: "CSV、設定ファイル、帳票連携、金融系データ連携を扱う開発者。",
    featuredTopics: ["CSV", "Properties", "NIO", "JSON", "XML", "全銀"],
  },
  {
    slug: "network",
    name: "ネットワーク",
    articleCount: 8,
    summary: "HTTP、TCP、UDP、SMTP、FTP まで Pure Java で仕組みを理解する。",
    priority: "high",
    purpose: "Java 標準 API で通信の基礎と実務上の注意点を押さえる。",
    audience: "API 連携、ソケット、通知連携を扱う開発者。",
    featuredTopics: ["HTTP", "TCP", "UDP", "SMTP", "FTP"],
  },
  {
    slug: "strings",
    name: "文字列",
    articleCount: 5,
    summary: "null 安全、書式化、正規表現、全半角など文字列処理の定番を扱う。",
    priority: "medium",
    purpose: "入力整形や文字列変換を再利用しやすい形に整理する。",
    audience: "フォーム入力やデータ整形を扱う開発者。",
    featuredTopics: ["null 安全", "書式化", "正規表現", "全半角"],
  },
  {
    slug: "collections",
    name: "コレクション",
    articleCount: 3,
    summary: "List、Map、Set と Stream API の実務パターンをまとめる。",
    priority: "medium",
    purpose: "一覧絞り込みや DTO 変換を読みやすく保守しやすい形で実装する。",
    audience: "業務一覧画面や集計処理で Stream を使う開発者。",
    featuredTopics: ["Stream.filter", "Stream.map", "List/Map/Set"],
  },
  {
    slug: "functional",
    name: "関数型",
    articleCount: 3,
    summary: "関数型インターフェースと合成、Stream と組み合わせた書き方を扱う。",
    priority: "medium",
    purpose: "関数型インターフェースを業務コードへ無理なく持ち込めるようにする。",
    audience: "Stream やコールバック設計を整理したい開発者。",
    featuredTopics: ["Function", "Predicate", "合成"],
  },
  {
    slug: "enum",
    name: "Enum",
    articleCount: 5,
    summary: "列挙型の基本から実務コード設計まで扱う。",
    priority: "medium",
    purpose: "定数管理と業務区分の表現を enum ベースで整理する。",
    audience: "状態管理や区分値変換を扱う開発者。",
    featuredTopics: ["定数管理", "コード値", "状態遷移"],
  },
  {
    slug: "records",
    name: "Record",
    articleCount: 4,
    summary: "Record と Sealed Classes を値オブジェクト設計の文脈で扱う。",
    priority: "medium",
    purpose: "値オブジェクト設計を簡潔に組み立てる。",
    audience: "DTO や集約境界の設計を整理したい開発者。",
    featuredTopics: ["Record", "Sealed Classes", "値オブジェクト"],
  },
  {
    slug: "reflection",
    name: "リフレクション",
    articleCount: 2,
    summary: "クラス情報取得とカスタムアノテーション処理を扱う。",
    priority: "medium",
    purpose: "リフレクションを限定的かつ安全に使う判断材料を提供する。",
    audience: "共通化や簡易フレームワーク実装を試す開発者。",
    featuredTopics: ["Class 情報", "Annotation", "メタデータ読取"],
  },
  {
    slug: "serialization",
    name: "シリアライズ",
    articleCount: 4,
    summary: "標準シリアライズとリスク、Externalizable を整理する。",
    priority: "medium",
    purpose: "標準シリアライズの制約と代替案を整理する。",
    audience: "一時保存や互換性維持を扱う開発者。",
    featuredTopics: ["Serializable", "Externalizable", "互換性"],
  },
  {
    slug: "encoding",
    name: "エンコーディング・圧縮",
    articleCount: 4,
    summary: "Base64 と ZIP/GZIP を中心に扱う。",
    priority: "medium",
    purpose: "文字コードと圧縮処理の基本を実務視点で整理する。",
    audience: "ファイル転送や添付データ処理を扱う開発者。",
    featuredTopics: ["Base64", "ZIP", "GZIP"],
  },
  {
    slug: "security",
    name: "セキュリティ",
    articleCount: 2,
    summary: "パスワードハッシュと AES-GCM を扱う。",
    priority: "medium",
    purpose: "標準 API で最低限必要な暗号処理を扱えるようにする。",
    audience: "認証やデータ保護を扱う開発者。",
    featuredTopics: ["ハッシュ", "AES-GCM", "鍵管理"],
  },
  {
    slug: "logging",
    name: "ロギング・例外処理",
    articleCount: 2,
    summary: "java.util.logging と例外チェーンの基本をまとめる。",
    priority: "medium",
    purpose: "障害調査に必要なログと例外設計の基礎を整理する。",
    audience: "保守運用や障害調査を担当する開発者。",
    featuredTopics: ["java.util.logging", "例外チェーン"],
  },
  {
    slug: "concurrency",
    name: "並行処理・メモリ",
    articleCount: 5,
    summary: "Atomic 操作、DB 採番、OOM、CompletableFuture、仮想スレッドを扱う。",
    priority: "medium",
    purpose: "競合やメモリ問題の入口を押さえる。",
    audience: "競合制御や性能課題に触れる開発者。",
    featuredTopics: ["Atomic", "採番", "OOM"],
  },
  {
    slug: "threading",
    name: "マルチスレッド",
    articleCount: 8,
    summary: "Thread、Lock、Condition、デッドロック対策まで扱う。",
    priority: "medium",
    purpose: "スレッド制御の基本と落とし穴を整理する。",
    audience: "並列処理やバッチ実装を扱う開発者。",
    featuredTopics: ["Thread", "Lock", "Condition", "デッドロック"],
  },
  {
    slug: "oop",
    name: "オブジェクト指向",
    articleCount: 3,
    summary: "interface / abstract class、SOLID、設計方針を扱う。",
    priority: "medium",
    purpose: "設計原則を Java コードへ落とし込む。",
    audience: "設計レビューやリファクタリングを行う開発者。",
    featuredTopics: ["SOLID", "interface", "abstract class"],
  },
  {
    slug: "patterns",
    name: "デザインパターン",
    articleCount: 23,
    summary: "GoF パターンを Java 標準ライブラリの文脈で整理する。",
    priority: "long_term",
    purpose: "パターン名だけでなく適用場面も合わせて整理する。",
    audience: "設計パターンを実務コードへ落としたい開発者。",
    featuredTopics: ["GoF", "適用判断", "標準ライブラリとの対応"],
  },
  {
    slug: "copying",
    name: "コピー",
    articleCount: 3,
    summary: "shallow / deep copy と落とし穴を整理する。",
    priority: "medium",
    purpose: "複製時の副作用を避ける設計を整理する。",
    audience: "DTO 変換やデータ複製を扱う開発者。",
    featuredTopics: ["shallow copy", "deep copy"],
  },
  {
    slug: "misc",
    name: "その他",
    articleCount: 1,
    summary: "外部プロセス実行など単発テーマを置く。",
    priority: "long_term",
    purpose: "他カテゴリに収まらない実務テーマを扱う。",
    audience: "単発の業務ユースケースを調べる開発者。",
    featuredTopics: ["外部プロセス実行"],
  },
  {
    slug: "testing",
    name: "テスト",
    articleCount: 10,
    summary: "JUnit 5、Mockito、AssertJ、Testcontainers、カバレッジ、テスト設計パターンまで実務テストを体系的に整理する。",
    priority: "medium",
    purpose: "JUnit の基本から実務テストの書き方を整理する。",
    audience: "JUnit や自動テストを導入したい開発者。",
    featuredTopics: ["JUnit 5", "Mockito", "AssertJ", "Testcontainers", "テスト設計"],
  },
  {
    slug: "gc",
    name: "GC",
    articleCount: 3,
    summary: "GC の基礎、JVM オプション、計測の入口を扱う。",
    priority: "long_term",
    purpose: "GC ログと JVM オプションの理解を補助する。",
    audience: "性能調査や JVM チューニングを行う開発者。",
    featuredTopics: ["GC ログ", "JVM オプション"],
  },
  {
    slug: "httpserver",
    name: "HTTP サーバー自作",
    articleCount: 8,
    summary: "Socket ベースの最小 HTTP サーバーを段階的に実装する。",
    priority: "long_term",
    purpose: "HTTP の基礎とサーバー構成を Socket レベルから理解する。",
    audience: "HTTP サーバーの仕組みを自分で理解したい開発者。",
    featuredTopics: ["Socket", "HTTP パーサー", "TODO サーバー"],
  },
  {
    slug: "perf",
    name: "パフォーマンス",
    articleCount: 2,
    summary: "処理時間とメモリ使用量の計測を扱う。",
    priority: "medium",
    purpose: "性能計測の基本を誤差込みで整理する。",
    audience: "処理速度やメモリ使用量を改善したい開発者。",
    featuredTopics: ["処理時間計測", "メモリ計測"],
  },
  {
    slug: "batch",
    name: "バッチ処理",
    articleCount: 8,
    summary: "Pure Java でバッチフレームワークを段階的に構築する連載。",
    priority: "medium",
    purpose: "外部ライブラリなしでバッチ処理の基本設計を体系的に整理する。",
    audience: "CSV取込・集計・連携バッチを実装する開発者。",
    featuredTopics: ["バッチ設計", "リトライ", "ログ設計", "エラーハンドリング"],
  },
]

export const PRIORITY_JAVA_TOPICS = ["営業日計算", "日本の祝日判定", "和暦・元号変換", "タイムゾーン処理", "消費税計算"]
